### ISSUE TITLE
Make the client to support simultaneous requests 

### ISSUE THREAD

**Issue by v-ladynev** [Bandwidth/java-bandwidth-iris#32]
There is an error, if client is used to perform two or more requests at the time. Better to use [OkHttp library](https://square.github.io/okhttp/)
```stacktrace
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.util.Asserts.check(Asserts.java:34) ~[httpcore-4.4.12.jar:4.4.12]
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:163) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:145) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:417) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.10.jar:4.5.10]
	at com.bandwidth.iris.sdk.IrisClient.executeRequest(IrisClient.java:169) ~[bandwidth-java-iris-sdk-1.10.jar:1.10]
	at com.bandwidth.iris.sdk.IrisClient.get(IrisClient.java:87) ~[bandwidth-java-iris-sdk-1.10.jar:1.10]
	at com.bandwidth.iris.sdk.IrisClient.get(IrisClient.java:71) ~[bandwidth-java-iris-sdk-1.10.jar:1.10]
```

**Comment by v-ladynev** [comment]
Guys, keep in mind your client is senseless for PROD without fixing this issue.

**Comment by ajrice6713** [comment]
Hey @v-ladynev,

We are planning a major upgrade of this SDK (and all others) in Q2/Q3 of this year - the `java-bandwidth-iris` package will be deprecated and the numbers api functionality will be added to our [java-sdk](https://github.com/Bandwidth/java-sdk) package, and it will utilize the okhttp-gson client which should resolve this issue
